# layer indices
layers:
  relu1_1: 1
  relu1_2: 3
  pool1: 4

  relu2_1: 6
  relu2_2: 8
  pool2: 9

  relu3_1: 11
  relu3_2: 13
  relu3_3: 15
  relu3_4: 17
  pool3: 18

  relu4_1: 20
  relu4_2: 22
  relu4_3: 24
  relu4_4: 26
  pool4: 27

  relu5_1: 29
  relu5_2: 31
  relu5_3: 33
  relu5_4: 35
  pool5: 36